export const metadata = {
  title: 'Next.js cabin',
  description: 'Generated by Next.js',
};

export default async function page() {
  const res = await fetch('https://jsonplaceholder.typicode.com/users');
  const data = await res.json();
  console.log(data);

  return (
    <header>
      <h1 className=' capitalize'>cabins</h1>
      <ul>
        {data.map((user) => (
          <li key={user.id}>{user.name}</li>
        ))}
      </ul>
    </header>
  );
}
