export const metadata = {
  title: 'Next.js cabin',
  description: 'Generated by Next.js',
};

export default function page() {
  return (
    <header>
      <h1 className=' capitalize'>cabins</h1>
    </header>
  );
}
